// Synthetic dataset for the pi-kanban static demo.
// Shapes mirror server.js responses; values are fictional.

(function () {
  const NOW = Date.now();
  const mins = (n) => new Date(NOW - n * 60_000).toISOString();
  const hours = (n) => mins(n * 60);

  const PROJ_API = 'C:\\demo\\acme-api';
  const PROJ_WEB = 'C:\\demo\\acme-web';
  const PROJ_PI = 'C:\\demo\\pi-kanban';

  const sessions = [
    {
      id: 'demo-0001-rate-limiter',
      name: 'demo-0001',
      slug: 'demo-0001',
      project: PROJ_API,
      cwd: PROJ_API,
      description: 'Add Redis-backed rate limiter',
      gitBranch: 'feat/rate-limiter',
      customTitle: 'rate-limiter',
      parentSession: null,
      taskCount: 4, pending: 1, inProgress: 1, completed: 2,
      createdAt: hours(3), modifiedAt: mins(8),
      hasMessages: true, hasActiveAgents: true, hasRunningAgents: true,
      hasWaitingForUser: false, hasRecentLog: true,
      jsonlPath: 'demo://acme-api/demo-0001.jsonl',
    },
    {
      id: 'demo-0002-auth-middleware',
      name: 'demo-0002',
      slug: 'demo-0002',
      project: PROJ_API,
      cwd: PROJ_API,
      description: 'Replace legacy auth middleware',
      gitBranch: 'chore/auth-rewrite',
      customTitle: 'auth-rewrite',
      parentSession: null,
      taskCount: 3, pending: 0, inProgress: 0, completed: 3,
      createdAt: hours(28), modifiedAt: hours(20),
      hasMessages: true, hasActiveAgents: false, hasRunningAgents: false,
      hasWaitingForUser: false, hasRecentLog: false,
      jsonlPath: 'demo://acme-api/demo-0002.jsonl',
    },
    {
      id: 'demo-0003-checkout-ui',
      name: 'demo-0003',
      slug: 'demo-0003',
      project: PROJ_WEB,
      cwd: PROJ_WEB,
      description: 'Refactor checkout flow into composable steps',
      gitBranch: 'feat/checkout-v2',
      customTitle: 'checkout-v2',
      parentSession: null,
      taskCount: 5, pending: 2, inProgress: 1, completed: 2,
      createdAt: hours(6), modifiedAt: mins(35),
      hasMessages: true, hasActiveAgents: false, hasRunningAgents: false,
      hasWaitingForUser: true, hasRecentLog: true,
      jsonlPath: 'demo://acme-web/demo-0003.jsonl',
    },
    {
      id: 'demo-0004-perf-audit',
      name: 'demo-0004',
      slug: 'demo-0004',
      project: PROJ_WEB,
      cwd: PROJ_WEB,
      description: 'Performance audit — initial load',
      gitBranch: 'main',
      customTitle: null,
      parentSession: null,
      taskCount: 0, pending: 0, inProgress: 0, completed: 0,
      createdAt: hours(48), modifiedAt: hours(46),
      hasMessages: true, hasActiveAgents: false, hasRunningAgents: false,
      hasWaitingForUser: false, hasRecentLog: false,
      jsonlPath: 'demo://acme-web/demo-0004.jsonl',
    },
    {
      id: 'demo-0005-theme-support',
      name: 'demo-0005',
      slug: 'demo-0005',
      project: PROJ_PI,
      cwd: PROJ_PI,
      description: 'Add configurable theme support',
      gitBranch: 'feat/theming',
      customTitle: 'theming',
      parentSession: null,
      taskCount: 2, pending: 0, inProgress: 0, completed: 2,
      createdAt: hours(72), modifiedAt: hours(70),
      hasMessages: true, hasActiveAgents: false, hasRunningAgents: false,
      hasWaitingForUser: false, hasRecentLog: false,
      jsonlPath: 'demo://pi-kanban/demo-0005.jsonl',
    },
  ];

  // Tasks keyed by sessionId.
  const tasksBySession = {
    'demo-0001-rate-limiter': [
      { id: '1', subject: 'Spike Redis token-bucket', status: 'completed',
        description: 'Prototype token-bucket using Redis INCR + EXPIRE. Confirm atomicity under concurrent load.',
        sessionId: 'demo-0001-rate-limiter', project: PROJ_API },
      { id: '2', subject: 'Wire middleware into Express app', status: 'completed',
        description: 'Add `rateLimit()` middleware. Apply globally, allow per-route override.',
        sessionId: 'demo-0001-rate-limiter', project: PROJ_API },
      { id: '3', subject: 'Add integration tests against real Redis', status: 'in_progress',
        description: 'Spin up Redis container in CI; cover burst, sustained, and reset scenarios.',
        sessionId: 'demo-0001-rate-limiter', project: PROJ_API },
      { id: '4', subject: 'Document tuning knobs', status: 'pending',
        description: 'README section: window size, burst capacity, key prefix, Redis connection.',
        sessionId: 'demo-0001-rate-limiter', project: PROJ_API },
    ],
    'demo-0002-auth-middleware': [
      { id: '1', subject: 'Audit current session token storage', status: 'completed',
        description: 'Identify all writes/reads, flag compliance gaps.',
        sessionId: 'demo-0002-auth-middleware', project: PROJ_API },
      { id: '2', subject: 'Implement new token store (httpOnly + rotated)', status: 'completed',
        description: 'Rotation on each refresh; revoke on logout.',
        sessionId: 'demo-0002-auth-middleware', project: PROJ_API },
      { id: '3', subject: 'Migrate routes off legacy middleware', status: 'completed',
        description: 'Move every router to the new auth middleware; remove the old module.',
        sessionId: 'demo-0002-auth-middleware', project: PROJ_API },
    ],
    'demo-0003-checkout-ui': [
      { id: '1', subject: 'Extract address form into <CheckoutAddress />', status: 'completed',
        description: 'Pure component, validates on blur, exposes onValid callback.',
        sessionId: 'demo-0003-checkout-ui', project: PROJ_WEB },
      { id: '2', subject: 'Move payment step behind feature flag', status: 'completed',
        description: 'Flag: checkout.payment-v2. Default off in prod.',
        sessionId: 'demo-0003-checkout-ui', project: PROJ_WEB },
      { id: '3', subject: 'Add review-and-confirm step', status: 'in_progress',
        description: 'Aggregates state from prior steps; shows totals + edit links.',
        sessionId: 'demo-0003-checkout-ui', project: PROJ_WEB },
      { id: '4', subject: 'A/B test step indicator placement', status: 'pending',
        description: 'Top vs. left rail. Decide on metric: completion rate.',
        sessionId: 'demo-0003-checkout-ui', project: PROJ_WEB },
      { id: '5', subject: 'Accessibility pass', status: 'pending',
        description: 'Keyboard order, focus traps in modal, aria-live for errors.',
        sessionId: 'demo-0003-checkout-ui', project: PROJ_WEB },
    ],
    'demo-0004-perf-audit': [],
    'demo-0005-theme-support': [
      { id: '1', subject: 'Design token schema', status: 'completed',
        description: '15 colors, derived dim/glow at runtime.',
        sessionId: 'demo-0005-theme-support', project: PROJ_PI },
      { id: '2', subject: 'Ship pi-light + pi-dark', status: 'completed',
        description: 'Default themes; user themes override by id.',
        sessionId: 'demo-0005-theme-support', project: PROJ_PI },
    ],
  };

  // Agents (subagents) keyed by sessionId.
  const agentsBySession = {
    'demo-0001-rate-limiter': {
      agents: [
        {
          agentId: 'agent-scout-001',
          type: 'scout', agentName: 'scout', status: 'stopped',
          startedAt: hours(2), stoppedAt: hours(2), updatedAt: hours(2),
          prompt: 'Inventory the Express middleware chain in src/app.ts. List every middleware in registration order, note which routes opt out, and flag any existing rate-limit, throttle, or quota implementations (including ad-hoc ones in route handlers).',
          description: '7 tools · 8.4K tokens · 1m12s',
          model: 'claude-sonnet-4-6', color: 'team',
          lastMessage: [
            '# Middleware inventory — src/app.ts',
            '',
            'Registration order (top-down):',
            '',
            '1. `helmet()` — security headers, default config.',
            '2. `cors({ origin: ALLOWED_ORIGINS, credentials: true })` — 4 allowed origins.',
            '3. `express.json({ limit: "1mb" })`.',
            '4. `requestId()` — custom, attaches `req.id` (uuid v4).',
            '5. `pinoHttp({ logger })` — request logging.',
            '6. `auth()` — verifies JWT, attaches `req.user` (skipped on `/health`, `/metrics`).',
            '7. **Router mount points** — `/v1/users`, `/v1/orders`, `/v1/webhooks`.',
            '',
            '## Rate-limit / throttle hits',
            '',
            '- No global rate-limiter. ✗',
            '- `src/routes/webhooks.ts:42` — ad-hoc `inFlight` Map keyed by `req.body.event_id` to drop duplicates within 5s. Not a true rate limiter; intent is dedupe.',
            '- `src/routes/users.ts:118` — `/forgot-password` route writes a `lastSentAt` to Redis (key `pwreset:{email}`) and returns 429 if hit twice within 60s. **Bespoke; should migrate to the new middleware.**',
            '- No usage of `express-rate-limit`, `rate-limiter-flexible`, or similar in package.json.',
            '',
            '## Recommendation',
            '',
            'Insert `rateLimit()` between `pinoHttp` (so log lines include `req.id`) and `auth` (so unauthenticated bursts are limited too). The forgot-password bespoke limiter can be deleted once per-route override is wired.',
          ].join('\n'),
        },
        {
          agentId: 'agent-reviewer-001',
          type: 'reviewer', agentName: 'reviewer', status: 'running',
          startedAt: mins(12), stoppedAt: null, updatedAt: mins(2),
          prompt: 'Review src/middleware/rate-limit.ts for: (1) race conditions in the INCR+EXPIRE pair, (2) key-collision risk across tenants, (3) behavior under Redis disconnect, (4) trust-proxy / spoofing exposure on req.ip.',
          description: '14 tools · 22K tokens · 4m30s · in progress',
          model: 'claude-opus-4-7', color: 'plan',
          lastMessage: [
            '## Review (in progress) — rate-limit.ts',
            '',
            '### 1. INCR/EXPIRE atomicity — **OK with caveat**',
            '',
            'The current implementation:',
            '',
            '```ts',
            'const count = await redis.incr(key);',
            'if (count === 1) await redis.expire(key, windowSec);',
            '```',
            '',
            'A crash between `incr` and `expire` would leave a key with no TTL → permanently blocked. Low probability, but recoverable. **Recommend `MULTI` or a Lua script**:',
            '',
            '```lua',
            'local v = redis.call("INCR", KEYS[1])',
            'if v == 1 then redis.call("EXPIRE", KEYS[1], ARGV[1]) end',
            'return v',
            '```',
            '',
            '### 2. Key collision — **RISK**',
            '',
            'Key format: `rl:{req.ip}:{req.path}`. Two issues:',
            '- Path is not normalized; `/v1/users/1` and `/v1/users/2` get separate buckets — likely intentional, but worth a comment.',
            '- No tenant prefix. If this service ever serves multiple tenants, a noisy-neighbor on shared IP (corporate NAT) starves the other.',
            '',
            'Suggest: `rl:{tenantId ?? "_"}:{req.ip}:{routeKey}` where `routeKey` is the matched Express path (`req.route?.path`), not `req.path`.',
            '',
            '### 3. Redis disconnect — **fail-open is correct, log is missing**',
            '',
            'The `try/catch` swallows the error and calls `next()`. That is the right default (fail-open beats taking the API down), but **there is no log line**. Operators will not notice a degraded limiter. Add:',
            '',
            '```ts',
            'req.log.warn({ err }, "rate-limit: redis unavailable, allowing request");',
            '```',
            '',
            '### 4. req.ip spoofing — **BLOCKER**',
            '',
            'The app does not set `app.set("trust proxy", …)`. Behind the load balancer, `req.ip` becomes the LB\'s internal IP — every request shares one bucket. Worse, if `trust proxy` is later set to `true` naively, clients can spoof `X-Forwarded-For`.',
            '',
            'Recommend: set `trust proxy` to the LB\'s subnet explicitly (`["10.0.0.0/8"]`), and document in the README. Verify in a test.',
            '',
            '_Still examining: behavior under Redis cluster failover, and the test for sustained-load flakiness._',
          ].join('\n'),
        },
      ],
      waitingForUser: false,
    },
    'demo-0003-checkout-ui': {
      agents: [
        {
          agentId: 'agent-planner-003',
          type: 'planner', agentName: 'planner', status: 'stopped',
          startedAt: hours(5), stoppedAt: hours(4), updatedAt: hours(4),
          prompt: 'Plan the checkout v2 split. We need three steps (address, payment, review) extracted from the current monolithic <Checkout/>. Identify shared state, prop boundaries, the routing model (single-page vs. step-routed), and migration risk.',
          description: '9 tools · 14K tokens · 2m48s',
          model: 'claude-opus-4-7', color: 'plan',
          lastMessage: [
            '# Checkout v2 — split plan',
            '',
            '## Components',
            '',
            '| Component                | Owns                                | Reads from context     |',
            '| ------------------------ | ----------------------------------- | ---------------------- |',
            '| `<CheckoutShell />`      | Step indicator, layout, navigation  | `step`                 |',
            '| `<CheckoutAddress />`    | Address form, validation            | `address`              |',
            '| `<CheckoutPayment />`    | Payment method selection + Stripe   | `payment`, `address`   |',
            '| `<CheckoutReview />`     | Summary + place-order button        | entire `checkoutState` |',
            '| `<CheckoutContext />`    | Reducer + persistence to sessionStorage | —                  |',
            '',
            '## Shared state shape',
            '',
            '```ts',
            'type CheckoutState = {',
            '  step: "address" | "payment" | "review";',
            '  address: AddressForm | null;',
            '  payment: { method: "card" | "paypal"; stripeToken?: string } | null;',
            '  totals: { subtotal: number; tax: number; shipping: number; total: number } | null;',
            '  flags: { paymentV2: boolean };',
            '};',
            '```',
            '',
            '## Routing',
            '',
            'Step-routed (`/checkout/address`, `/checkout/payment`, `/checkout/review`). Pros: deep-linkable, browser-back works; Cons: requires guard rails (cannot land on `/payment` with no address). Use a `<RequireStep />` wrapper.',
            '',
            '## Migration risk',
            '',
            '- **Analytics events**: existing `checkout_completed` event fires from the monolith. Need to re-emit from `<CheckoutReview />` with the same shape. Add a snapshot test.',
            '- **A11y regression**: focus management between steps. Add `useEffect` to focus the step heading on mount.',
            '- **Feature flag**: gate the entire v2 tree behind `checkout.payment-v2`; default off in prod.',
            '',
            '## Open questions (need your call)',
            '',
            '1. Server-computed totals (extra round-trip) vs. client-mirrored (simpler, drift risk)?',
            '2. Should the step indicator live above the form (top) or in a left rail? Affects mobile.',
          ].join('\n'),
        },
        {
          agentId: 'agent-reviewer-003',
          type: 'reviewer', agentName: 'reviewer', status: 'stopped',
          startedAt: hours(2), stoppedAt: hours(2), updatedAt: hours(2),
          prompt: 'Review the extracted <CheckoutAddress /> for a11y, validation correctness, and re-render churn.',
          description: '6 tools · 10K tokens · 1m45s',
          model: 'claude-sonnet-4-6', color: 'team',
          lastMessage: [
            '## Review — <CheckoutAddress />',
            '',
            '**Verdict:** ship-ready with two small fixes.',
            '',
            '### Findings',
            '',
            '- ✅ Validates on blur (matches plan), exposes `onValid` callback as designed.',
            '- ✅ All inputs have associated `<label>` with `htmlFor`. Error messages use `aria-describedby`.',
            '- ⚠️  Postal code regex is US-only (`^\\d{5}(-\\d{4})?$`) but the form is rendered on `/checkout/address` regardless of country. Either: render-by-country, or relax to `^[\\w \\-]{3,10}$`.',
            '- ⚠️  `useEffect(() => onValid(isValid), [isValid])` — `onValid` from parent is not memoised, so this runs on every parent render. Wrap in `useCallback` upstream or compare via ref.',
            '- ✅ No re-renders on keystroke beyond the field itself (verified with React DevTools profiler).',
            '',
            '### Test coverage',
            '',
            'Missing: blur on empty required field. Add a test that asserts the error appears with the correct `aria-describedby` link.',
          ].join('\n'),
        },
      ],
      waitingForUser: true,
    },
  };

  // Messages (Session Log) keyed by sessionId.
  const baseMsg = (text, mins_ago, role = 'assistant') => ({
    type: role, role,
    text,
    timestamp: mins(mins_ago),
    model: role === 'assistant' ? 'claude-sonnet-4-6' : null,
    provider: role === 'assistant' ? 'anthropic' : null,
    usage: role === 'assistant' ? {
      input: 1240, output: 320, cacheRead: 18420, cacheWrite: 0,
      totalTokens: 19980, cost: { input: 0.0037, output: 0.0048, cacheRead: 0.0014, cacheWrite: 0, total: 0.0099 },
    } : null,
  });

  const messagesBySession = {
    'demo-0001-rate-limiter': [
      baseMsg('Add a rate limiter to the API, Redis-backed.', 180, 'user'),
      baseMsg('I\'ll spike a token-bucket on Redis using INCR + EXPIRE. Sketching the middleware shape first.', 178),
      baseMsg('Found existing middleware chain in `src/app.ts` — slot the limiter after `cors()` and before `auth()`.', 165),
      baseMsg('The atomicity story: INCR returns the new count, EXPIRE on first hit. Race window is acceptable for a 60s window.', 130),
      baseMsg('Wired in `rateLimit()` — globally 100 req/min, override per-route via `rateLimit({ max: 10 })`.', 100),
      baseMsg('Now writing integration tests with a real Redis container in CI.', 30),
      baseMsg('Burst test passing. Sustained-load test flaky — investigating clock skew.', 12),
      baseMsg('Reviewer agent flagged proxy-header spoofing on `req.ip`. Will add `trust proxy` config note.', 2),
    ],
    'demo-0002-auth-middleware': [
      baseMsg('Legal flagged session-token storage. Replace the auth middleware.', 1700, 'user'),
      baseMsg('Audited storage. Tokens were written to a non-httpOnly cookie. Flagged 6 routes that read them client-side — need to migrate.', 1640),
      baseMsg('New token store landed: httpOnly cookies, rotated on refresh, revoked on logout.', 1500),
      baseMsg('All routes migrated. Old middleware removed. Tests green.', 1200),
    ],
    'demo-0003-checkout-ui': [
      baseMsg('Refactor the checkout flow — three steps, each its own component.', 360, 'user'),
      baseMsg('Planner agent produced the split. Starting with `<CheckoutAddress />` — pure, validated, exposes `onValid`.', 320),
      baseMsg('Address form done. Payment step behind `checkout.payment-v2` flag, off in prod.', 200),
      baseMsg('Now wiring the review-and-confirm step. Need a decision on totals: server-computed vs client-mirrored.', 35),
      baseMsg('I\'ll defer to you on totals — server-computed is safer but adds a round-trip.', 34),
    ],
    'demo-0004-perf-audit': [
      baseMsg('Run a performance audit on the landing page.', 2880, 'user'),
      baseMsg('LCP 3.4s, CLS 0.08, INP 240ms. Biggest win: defer the analytics bundle, currently render-blocking.', 2870),
      baseMsg('Drafted a one-pager with prioritized fixes. No code changes yet.', 2760),
    ],
    'demo-0005-theme-support': [
      baseMsg('Add configurable theming.', 4320, 'user'),
      baseMsg('Design token schema settled: 15 colors, derived dim/glow at runtime. Built-ins: pi-light, pi-dark, kanban-default, kanban-dark-default.', 4300),
      baseMsg('Themes load from `~/.pi/agent/kanban/themes/`. Env vars override settings.json.', 4220),
    ],
  };

  // Plans keyed by sessionId.
  const plansBySession = {
    'demo-0001-rate-limiter': {
      sessionId: 'demo-0001-rate-limiter',
      content: '# Rate limiter plan\n\n1. Token-bucket on Redis (INCR + EXPIRE)\n2. Middleware: global default, per-route override\n3. Tests: burst, sustained, reset\n4. Docs: tuning knobs, proxy/trust config\n',
      timestamp: hours(2),
    },
    'demo-0003-checkout-ui': {
      sessionId: 'demo-0003-checkout-ui',
      content: '# Checkout v2\n\n- `<CheckoutAddress />` — validated, onValid\n- `<CheckoutPayment />` — flagged behind `checkout.payment-v2`\n- `<CheckoutReview />` — aggregates, edit links\n- Shared `CheckoutContext` for cross-step state\n',
      timestamp: hours(5),
    },
  };

  // Projects list (shape: array of { project, cwd, sessionCount, ... }).
  const projects = [
    { path: PROJ_API, project: PROJ_API, cwd: PROJ_API, encoded: '--C--demo-acme-api--', sessionCount: 2, modifiedAt: mins(8), lastModified: mins(8) },
    { path: PROJ_WEB, project: PROJ_WEB, cwd: PROJ_WEB, encoded: '--C--demo-acme-web--', sessionCount: 2, modifiedAt: mins(35), lastModified: mins(35) },
    { path: PROJ_PI,  project: PROJ_PI,  cwd: PROJ_PI,  encoded: '--C--demo-pi-kanban--', sessionCount: 1, modifiedAt: hours(70), lastModified: hours(70) },
  ];

  // Themes (matches /api/themes shape: { light, dark, config }).
  const themes = {
    light: {
      name: 'pi-light', displayName: 'pi.dev Light', mode: 'light',
      colors: {
        bgDeep:'#ebe7e4', bgSurface:'#f4f1ee', bgElevated:'#ddd8d3', bgHover:'#d2ccc6',
        border:'#a09b94', textPrimary:'#0a0a0a', textSecondary:'#444', textTertiary:'#666',
        textMuted:'#888', accent:'#2f5f8a', accentText:'#1f4566',
        success:'#1a8a5a', warning:'#b07d0a', plan:'#5a7a5a',
      },
    },
    dark: {
      name: 'pi-dark', displayName: 'pi.dev Dark', mode: 'dark',
      colors: {
        bgDeep:'#0d1116', bgSurface:'#161d27', bgElevated:'#212730', bgHover:'#252f3d',
        border:'#495059', textPrimary:'#ebe7e4', textSecondary:'#d5d8db',
        textTertiary:'#9fa4ab', textMuted:'#757d89',
        accent:'#6a9fcc', accentText:'#8fb6d8',
        success:'#4ade80', warning:'#fbbf24', plan:'#c084fc',
      },
    },
    config: { lightId: 'pi-light', darkId: 'pi-dark' },
  };

  window.__PI_KANBAN_DEMO__ = {
    sessions, tasksBySession, agentsBySession,
    messagesBySession, plansBySession, projects, themes,
  };
})();
